import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'doc',
      id: 'index',
      label: 'Overview',
    },
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: [
        'getting-started/setup',
        'getting-started/first-plugin',
      ],
    },
    {
      type: 'category',
      label: 'API Reference',
      collapsed: false,
      items: [
        'api-reference/plugin-base',
        'api-reference/chat-commands',
        'api-reference/console-commands',
        'api-reference/timers',
        'api-reference/entities',
        'api-reference/players',
        'api-reference/networking',
        'api-reference/particles',
        'api-reference/modifiers',
        'api-reference/damage',
        'api-reference/game-events',
        'api-reference/entity-io',
        'api-reference/configuration',
        'api-reference/heroes',
        'api-reference/precaching',
        'api-reference/tracing',
        'api-reference/world-text',
        {
          type: 'category',
          label: 'Class Reference',
          collapsed: true,
          items: [
            { type: 'autogenerated', dirName: 'api-reference/generated' },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      collapsed: false,
      items: [
        'guides/plugin-lifecycle',
        'guides/damage-system',
        'guides/team-and-hero-management',
        'guides/chat-and-hud',
      ],
    },
    {
      type: 'category',
      label: 'Examples',
      collapsed: false,
      items: [
        'examples/roll-the-dice',
        'examples/item-rotation',
        'examples/deathmatch',
        'examples/scourge',
      ],
    },
  ],
};

export default sidebars;
